### ISSUE TITLE
run train.py occur error

### ISSUE THREAD

**Issue by zhenyezi** [liuwei16/ALFNet#1]
when I run train.py ,I run into some error
File "/ghome/zhenye/ALFNet-master/keras_alfnet/data_generators.py", line 7, in <module>
    from .utils.cython_bbox import bbox_overlaps
ImportError: No module named cython_bbox
besides,
File "/ghome/zhenye/ALFNet-master/keras_alfnet/data_generators.py", line 8, in <module>
    from .utils.bbox import box_op
ImportError: No module named bbox
I want to ask the author whether miss the two functions or I miss some important operations?

**Comment by zhangxydlut** [comment]
I have the same problem.

**Comment by MADONOKOUKI** [comment]
@zhenyezi @zhenyezi 
num of training samples: 2112
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    from keras_alfnet.model.model_1step import Model_1step
  File "/var/docker/share/madono/summer/ALFNet/keras_alfnet/model/model_1step.py", line 1, in <module>
    from .base_model import Base_model
  File "/var/docker/share/madono/summer/ALFNet/keras_alfnet/model/base_model.py", line 2, in <module>
    from keras_alfnet import data_generators
  File "/var/docker/share/madono/summer/ALFNet/keras_alfnet/data_generators.py", line 7, in <module>
    from .utils.cython_bbox import bbox_overlaps
ImportError: No module named cython_bbox
I also have similar problems...

**Comment by pnnnnnnn** [comment]
git clone --recursive https://github.com/rbgirshick/py-faster-rcnn.git and cd py-faster-rcnn/lib and make
then copy the utils document from py-faster-rcnn to the utils document from ALFNet
then uncomment all "from .utils.bbox import box_op" and change "box_op" to "bbox_overlaps"
it works for me...

**Comment by yongqiangzhang1** [comment]
> git clone --recursive https://github.com/rbgirshick/py-faster-rcnn.git and cd py-faster-rcnn/lib and make
> then copy the utils document from py-faster-rcnn to the utils document from ALFNet
> then uncomment all "from .utils.bbox import box_op" and change "box_op" to "bbox_overlaps"
> it works for me...

Is the trained results right?

**Comment by yongqiangzhang1** [comment]
@pnnnnnnn , Is the trained results right?

**Comment by yongqiangzhang1** [comment]
@pnnnnnnn , what is the meaning of "uncomment all "from .utils.bbox import box_op" and change "box_op" to "bbox_overlaps""? comment or uncomment?

**Comment by pnnnnnnn** [comment]
> @pnnnnnnn , what is the meaning of "uncomment all "from .utils.bbox import box_op" and change "box_op" to "bbox_overlaps""? comment or uncomment?
oh, sorry, it's "comment"
1. comment all "from .utils.bbox import box_op"
2.  change the remaining "box_op" to "bbox_overlaps"

**Comment by pnnnnnnn** [comment]
> @pnnnnnnn , what is the meaning of "uncomment all "from .utils.bbox import box_op" and change "box_op" to "bbox_overlaps""? comment or uncomment?


oh, sorry, it's "comment"
comment all "from .utils.bbox import box_op"
change the remaining "box_op" to "bbox_overlaps"

**Comment by yongqiangzhang1** [comment]
@pnnnnnnn do you check the box_op and bbox_overlaps have the same function?

**Comment by pnnnnnnn** [comment]
> @pnnnnnnn do you check the box_op and bbox_overlaps have the same function?

there's no box_op function

**Comment by VideoObjectSearch** [comment]
@yongqiangzhang1 @zhangxydlut @MADONOKOUKI @pnnnnnnn
Please try this compiled document 
[utils.zip](https://github.com/liuwei16/ALFNet/files/2424399/utils.zip)

**Comment by VideoObjectSearch** [comment]
@yongqiangzhang1 
You can have a try.
[nms.zip](https://github.com/liuwei16/ALFNet/files/2426261/nms.zip)

**Comment by yongqiangzhang1** [comment]
nms works, thank you very much.

**Comment by Chen94yue** [comment]
> > @pnnnnnnn , Is the trained results right?
> 
> still training, for now i've trained for 70 epochs and the total loss dropped from 0.66 to 0.19

Did you get the same MR as the paper?

**Comment by pnnnnnnn** [comment]
> > > @pnnnnnnn , Is the trained results right?
> > 
> > 
> > still training, for now i've trained for 70 epochs and the total loss dropped from 0.66 to 0.19
> 
> Did you get the same MR as the paper?

not yet(?), i've trained for 200 epochs(2k iterations per epoch, batchsize 4, gpu 1050ti) and got 16.53 on the best model, and now i'm decreasing the lr from 1e-4 to 1e-5 for 100 epochs

**Comment by pnnnnnnn** [comment]
> > > > > @pnnnnnnn , Is the trained results right?
> > > > 
> > > > 
> > > > still training, for now i've trained for 70 epochs and the total loss dropped from 0.66 to 0.19
> > > 
> > > 
> > > Did you get the same MR as the paper?
> > 
> > 
> > not yet(?), i've trained for 200 epochs(2k iterations per epoch, batchsize 4, gpu 1050ti) and got 16.53 on the best model, and now i'm decreasing the lr from 1e-4 to 1e-5 for 100 epochs
> 
> Hi, still the question, did you get the same MR as the paper? The best score I have got is 16.33. A BIG GAP.

the best i've got is 13.18, maybe it's because my small batchsize(only 4) that i can't reach 12.01

**Comment by sxl1995** [comment]
> @yongqiangzhang1
> You can have a try.
> [nms.zip](https://github.com/liuwei16/ALFNet/files/2426261/nms.zip)

I use your nms.zip, but there is an error ImportError:libcudart.so.8.0: cannot open shared object file: No such file or director. Maybe because we have different cuda versions? My cuda is 7.5. How can i compile the nms file ?

**Comment by sxl1995** [comment]
I use your nms.zip, but there is an error ImportError:libcudart.so.8.0: cannot open shared object file: No such file or director. Maybe because we have different cuda versions? My cuda is 7.5. How can i compile the nms file ?

**Comment by ou525** [comment]
hi, when i run the test.py,  also have the same problem.

**Comment by TuanZ7** [comment]
> @yongqiangzhang1
> You can have a try.
> [nms.zip](https://github.com/liuwei16/ALFNet/files/2426261/nms.zip)

hi, @VideoObjectSearch , when i use the nms.zip, i have the problem:
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

i use CUDA9.0, how can i compile to make it work?

**Comment by weizheliu** [comment]
> > @yongqiangzhang1
> > You can have a try.
> > [nms.zip](https://github.com/liuwei16/ALFNet/files/2426261/nms.zip)
> 
> hi, @VideoObjectSearch , when i use the nms.zip, i have the problem:
> ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
> 
> i use CUDA9.0, how can i compile to make it work?

I meet the same problem, do you find the cuda 9 version of nms?

**Comment by whitenightwu** [comment]
> > > @yongqiangzhang1
> > > You can have a try.
> > > [nms.zip](https://github.com/liuwei16/ALFNet/files/2426261/nms.zip)
> > 
> > 
> > hi, @VideoObjectSearch , when i use the nms.zip, i have the problem:
> > ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
> > i use CUDA9.0, how can i compile to make it work?
> 
> I meet the same problem, do you find the cuda 9 version of nms?

you can try [nms.zip](https://github.com/liuwei16/ALFNet/files/2982714/nms.zip)

**Comment by xiefeiwhu** [comment]
> hi, when i run the test.py, also have the same problem. i use python3.5 @VideoObjectSearch
> Traceback (most recent call last):
> File "test.py", line 32, in
> from keras_alfnet.model.model_1step import Model_1step
> File "/home/ou/workplace/ALFNet/keras_alfnet/model/model_1step.py", line 1, in
> from .base_model import Base_model
> File "/home/ou/workplace/ALFNet/keras_alfnet/model/base_model.py", line 2, in
> from keras_alfnet import data_generators
> File "/home/ou/workplace/ALFNet/keras_alfnet/data_generators.py", line 7, in
> from .utils.cython_bbox import bbox_overlaps
> ImportError: /home/ou/workplace/ALFNet/keras_alfnet/utils/cython_bbox.so: undefined symbol: _Py_ZeroStruct

hi, i meet the same question, have you solved it?

**Comment by nankeermeng** [comment]
@yongqiangzhang1 @pnnnnnnn
follow the code I can train 150 epochs, but when i run the test.py using the train result resnet_e3_l1.15433712553.hdf5 , I cannot get test result, the val_det.txt is empty, why?

**Comment by nankeermeng** [comment]
@yongqiangzhang1 @pnnnnnnn
is a problem that cache files? how generate cache files?
